-- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM (SELECT *
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE "%INTACT%") A     
    JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SEX_UPON_OUTCOME IN ('SPAYED FEMALE', 'NEUTERED MALE')
ORDER BY B.ANIMAL_ID